name: Monitor

on:
  push:
    branches:
      - 'main'

jobs:
  check-accessibility:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: install npm dependencies
        run: npm ci
      - name: run automated accessibility checks
        run: npm run test:e2e
